//-----------------------------------------------------------------------------
//                
//							文字の表示
//														programed by N-KAITO
//-----------------------------------------------------------------------------

#include    "../flame_include.h"

#define FONT_TEXTURE_SIZE		48
#define ALPHABET_TEXTURE_SIZE	128
#define CURSOR_POINT			work9[P]
#define FONT_SIZE				fwork9[X]
#define FONT_INTERVAL_X			fwork8[X]
#define FONT_INTERVAL_Y			fwork8[Y]

//この二つは永久欠番
#define TEXTURE_FONT_AS		DATA_MAX - 1
#define TEXTURE_FONT_JS		DATA_MAX - 2

#define PRI_FONT			100

PARTS_RECT font_rect[] = 
{
	//--------------------------------------------------------ひらがな------------------------------------------------------------------------------------------
	//あ行
	{FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x00
	{FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x01
	{FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x02
	{FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x03
	{FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x04

	//か行			  
	{FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x05
	{FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x06
	{FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x07
	{FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x08
	{FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x09

	//さ行	 						 																							
	{FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x0A
	{FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x0B
	{FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x0C
	{FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x0D
	{FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x0E

	//た行					 																							
	{FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x0F
	{FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x10
	{FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x11
	{FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x12
	{FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x13

	//な行						 																							
	{FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x14
	{FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x15
	{FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x16
	{FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x17
	{FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x18

	//は行				 																							
	{FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x19
	{FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x1A
	{FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x1B
	{FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x1C
	{FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x1D

	//ま行				 																							
	{FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x1E
	{FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x1F
	{FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x20
	{FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x21
	{FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x22

	//や行	 						 																							
	{FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x23
	{FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x24
	{FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x25
	{FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x26
	{FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x27

	//ら行					 																							
	{FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x28
	{FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x29
	{FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x2A
	{FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x2B
	{FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x2C

	//わ行			 						 																						 
	{FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x2D
	{FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x2E
	{FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x2F
	// ー
	{FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x30
	// ～
	{FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x31

	//が行
	{FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x32
	{FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x33
	{FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x34
	{FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x35
	{FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x36

	//ざ行
	{FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x37
	{FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x38
	{FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x39
	{FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x3A
	{FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x3B

	//だ行
	{FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x3C
	{FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x3D
	{FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x3E
	{FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x3F
	{FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x40

	//ば行
	{FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x41
	{FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x42
	{FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x43
	{FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x44
	{FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x45

	//ぱ行
	{FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x46
	{FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x47
	{FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x48
	{FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x49
	{FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x4A

	//--------------------------------------------------------カタカナ---------------------------------------------------------------------------------------																																				  
	//ア行																																			
	{ FONT_TEXTURE_SIZE * 10, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x4B
	{ FONT_TEXTURE_SIZE * 11, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x4C
	{ FONT_TEXTURE_SIZE * 12, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x4D
	{ FONT_TEXTURE_SIZE * 13, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x4E
	{ FONT_TEXTURE_SIZE * 14, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x4F

	//カ行																																			
	{ FONT_TEXTURE_SIZE * 10, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x50
	{ FONT_TEXTURE_SIZE * 11, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x51
	{ FONT_TEXTURE_SIZE * 12, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x52
	{ FONT_TEXTURE_SIZE * 13, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x53
	{ FONT_TEXTURE_SIZE * 14, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x54

	//サ行																																			
	{ FONT_TEXTURE_SIZE * 10, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x55
	{ FONT_TEXTURE_SIZE * 11, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x56
	{ FONT_TEXTURE_SIZE * 12, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x57
	{ FONT_TEXTURE_SIZE * 13, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x58
	{ FONT_TEXTURE_SIZE * 14, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x59

	//タ行																																			
	{ FONT_TEXTURE_SIZE * 10, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x5A
	{ FONT_TEXTURE_SIZE * 11, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x5B
	{ FONT_TEXTURE_SIZE * 12, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x5C
	{ FONT_TEXTURE_SIZE * 13, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x5D
	{ FONT_TEXTURE_SIZE * 14, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x5E

	//ナ行																																			  
	{ FONT_TEXTURE_SIZE * 10, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x5F
	{ FONT_TEXTURE_SIZE * 11, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x60
	{ FONT_TEXTURE_SIZE * 12, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x61
	{ FONT_TEXTURE_SIZE * 13, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x62
	{ FONT_TEXTURE_SIZE * 14, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x63

	//ハ行																																			
	{ FONT_TEXTURE_SIZE * 10, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x64
	{ FONT_TEXTURE_SIZE * 11, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x65
	{ FONT_TEXTURE_SIZE * 12, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x66
	{ FONT_TEXTURE_SIZE * 13, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x67
	{ FONT_TEXTURE_SIZE * 14, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x68

	//マ行																																			  
	{FONT_TEXTURE_SIZE * 10, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x69
	{ FONT_TEXTURE_SIZE * 11, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x6A
	{ FONT_TEXTURE_SIZE * 12, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x6B
	{ FONT_TEXTURE_SIZE * 13, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x6C
	{ FONT_TEXTURE_SIZE * 14, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x6D

	//ヤ行																																			
	{ FONT_TEXTURE_SIZE * 10, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x6E
	{ FONT_TEXTURE_SIZE * 11, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x6F
	{ FONT_TEXTURE_SIZE * 12, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x70
	{ FONT_TEXTURE_SIZE * 13, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x71
	{ FONT_TEXTURE_SIZE * 14, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x72

	//ラ行																																			  
	{ FONT_TEXTURE_SIZE * 10, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x73
	{ FONT_TEXTURE_SIZE * 11, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x74
	{ FONT_TEXTURE_SIZE * 12, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x75
	{ FONT_TEXTURE_SIZE * 13, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x76
	{ FONT_TEXTURE_SIZE * 14, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x77

	//ワ行																																			
	{ FONT_TEXTURE_SIZE * 10, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x78
	{ FONT_TEXTURE_SIZE * 11, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x79
	{ FONT_TEXTURE_SIZE * 12, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x7A

	//ガ行																																			  
	{ FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x7B
	{ FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x7C
	{ FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x7D
	{ FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x7E
	{ FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x7F

	//ザ行																																			  
	{FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x80
	{FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x81
	{FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x82
	{FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x83
	{FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x84

	//ダ行																																			  
	{FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x85
	{FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x86
	{FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x87
	{FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x88
	{FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x89

	//バ行																																			  
	{FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x8A
	{FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x8B
	{FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x8C
	{FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x8D
	{FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x8E

	//パ行																																			  
	{FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x8F
	{FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x90
	{FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x91
	{FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x92
	{FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x93

	//--------------------------------------------------------ちっちゃいやつ------------------------------------------------------------------------------
	//ゃ	　ゅ　ょ																																   
	{FONT_TEXTURE_SIZE * 13, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x94
	{FONT_TEXTURE_SIZE * 14, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x95
	{FONT_TEXTURE_SIZE * 15, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x96
	//ャ　ュ　ョ
	{FONT_TEXTURE_SIZE * 16, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x97
	{FONT_TEXTURE_SIZE * 17, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x98																															   
	{FONT_TEXTURE_SIZE * 18, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x99
	//っ
	{FONT_TEXTURE_SIZE * 19, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x9A
	//ッ
	{FONT_TEXTURE_SIZE * 20, FONT_TEXTURE_SIZE * 9, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x9B

	//--------------------------------------------------------漢字---------------------------------------------------------------------------------------	
	//設
	{FONT_TEXTURE_SIZE * 15, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x9C
	//定
	{FONT_TEXTURE_SIZE * 16, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x9D
	//決
	{FONT_TEXTURE_SIZE * 17, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x9E
	//戻
	{FONT_TEXTURE_SIZE * 18, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0x9F
	//未
	{FONT_TEXTURE_SIZE * 19, FONT_TEXTURE_SIZE * 0, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xA0
	//上
	{FONT_TEXTURE_SIZE * 15, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xA1
	//下
	{FONT_TEXTURE_SIZE * 16, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xA2
	//左
	{FONT_TEXTURE_SIZE * 17, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xA3
	//右
	{FONT_TEXTURE_SIZE * 18, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xA4


	//--------------------------------------------------------記号---------------------------------------------------------------------------------------	
	//	+
	{FONT_TEXTURE_SIZE * 15, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xA5
	//	-										  
	{FONT_TEXTURE_SIZE * 16, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xA6
	//	×										  
	{FONT_TEXTURE_SIZE * 17, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xA7
	//	÷										  
	{FONT_TEXTURE_SIZE * 18, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xA8
	//	*										  
	{FONT_TEXTURE_SIZE * 19, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xA9
	//	/
	{FONT_TEXTURE_SIZE * 20, FONT_TEXTURE_SIZE * 8, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xAA
	//	↑
	{FONT_TEXTURE_SIZE * 15, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xAB
	//	↓
	{FONT_TEXTURE_SIZE * 16, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xAC
	//	←
	{FONT_TEXTURE_SIZE * 17, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xAD
	//	→
	{FONT_TEXTURE_SIZE * 18, FONT_TEXTURE_SIZE * 2, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xAE

	//--------------------------------------------------------数字---------------------------------------------------------------------------------------	
	//0
	{FONT_TEXTURE_SIZE * 15, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xAF
	//1
	{FONT_TEXTURE_SIZE * 16, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xB0
	//2
	{FONT_TEXTURE_SIZE * 17, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xB1
	//3
	{FONT_TEXTURE_SIZE * 18, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xB2
	//4
	{FONT_TEXTURE_SIZE * 19, FONT_TEXTURE_SIZE * 6, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xB3
	//5
	{FONT_TEXTURE_SIZE * 15, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xB4
	//6
	{FONT_TEXTURE_SIZE * 16, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xB5
	//7
	{FONT_TEXTURE_SIZE * 17, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xB6
	//8
	{FONT_TEXTURE_SIZE * 18, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xB7
	//9
	{FONT_TEXTURE_SIZE * 19, FONT_TEXTURE_SIZE * 7, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE / 2, FONT_TEXTURE_SIZE / 2 },	//0xB8

	//--------------------------------------------------------枠組み---------------------------------------------------------------------------------------	
	//6角形(グリーン)
	{FONT_TEXTURE_SIZE * 15, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 5 / 2, FONT_TEXTURE_SIZE / 2 },	//0xB9
	//6角形(グレー)
	{FONT_TEXTURE_SIZE * 15, FONT_TEXTURE_SIZE * 4, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 5 / 2, FONT_TEXTURE_SIZE / 2 },	//0xBA
	//6角形(ブルー)
	{FONT_TEXTURE_SIZE * 15, FONT_TEXTURE_SIZE * 3, FONT_TEXTURE_SIZE * 5, FONT_TEXTURE_SIZE * 1, FONT_TEXTURE_SIZE * 5 / 2, FONT_TEXTURE_SIZE / 2 },	//0xBB

	//A～Z
	{ ALPHABET_TEXTURE_SIZE *  0, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xBC	A
	{ ALPHABET_TEXTURE_SIZE *  1, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xBD	B
	{ ALPHABET_TEXTURE_SIZE *  2, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xBE	C
	{ ALPHABET_TEXTURE_SIZE *  3, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xBF  D
	{ ALPHABET_TEXTURE_SIZE *  4, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xC0	E
	{ ALPHABET_TEXTURE_SIZE *  5, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xC1	F
	{ ALPHABET_TEXTURE_SIZE *  6, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xC2	G
	{ ALPHABET_TEXTURE_SIZE *  7, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xC3	H
	{ ALPHABET_TEXTURE_SIZE *  8, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xC4	I
	{ ALPHABET_TEXTURE_SIZE *  9, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xC5	J
	{ ALPHABET_TEXTURE_SIZE * 10, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xC6	K
	{ ALPHABET_TEXTURE_SIZE * 11, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xC7	L
	{ ALPHABET_TEXTURE_SIZE * 12, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xC8	M
	{ ALPHABET_TEXTURE_SIZE * 13, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xC9	N
	{ ALPHABET_TEXTURE_SIZE * 14, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xCA	O
	{ ALPHABET_TEXTURE_SIZE * 15, ALPHABET_TEXTURE_SIZE * 0, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xCB	P
	{ ALPHABET_TEXTURE_SIZE *  0, ALPHABET_TEXTURE_SIZE * 1, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xCC	Q
	{ ALPHABET_TEXTURE_SIZE *  1, ALPHABET_TEXTURE_SIZE * 1, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xCD	R
	{ ALPHABET_TEXTURE_SIZE *  2, ALPHABET_TEXTURE_SIZE * 1, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xCE	S
	{ ALPHABET_TEXTURE_SIZE *  3, ALPHABET_TEXTURE_SIZE * 1, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xCF	T
	{ ALPHABET_TEXTURE_SIZE *  4, ALPHABET_TEXTURE_SIZE * 1, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xD0	U
	{ ALPHABET_TEXTURE_SIZE *  5, ALPHABET_TEXTURE_SIZE * 1, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xD1	V
	{ ALPHABET_TEXTURE_SIZE *  6, ALPHABET_TEXTURE_SIZE * 1, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xD2	W
	{ ALPHABET_TEXTURE_SIZE *  7, ALPHABET_TEXTURE_SIZE * 1, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xD3	X
	{ ALPHABET_TEXTURE_SIZE *  8, ALPHABET_TEXTURE_SIZE * 1, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xD3	Y
	{ ALPHABET_TEXTURE_SIZE *  9, ALPHABET_TEXTURE_SIZE * 1, ALPHABET_TEXTURE_SIZE,  ALPHABET_TEXTURE_SIZE, ALPHABET_TEXTURE_SIZE / 2, ALPHABET_TEXTURE_SIZE / 2 },	//0xD3	Z
};																																											

//-------------------------------------------------------------------------------------------------
//	文字列の表示
//-------------------------------------------------------------------------------------------------
void font_pop_drawfunc( TASK *ap )
{
	TASK spr;
	FLOAT font_scale;
	SINT32* string_addr;
	SINT32 string_box;
	SINT32 pop_font_counter = 0;


	string_addr = ap->work_p[X];
	string_box = *string_addr;

	TASK_init(&spr);

	spr.pos[X] = ap->pos[X];
	spr.pos[Y] = ap->pos[Y];
	spr.pos[Z] = ap->pos[Z];
	spr.base_color[0][0] = ap->base_color[0][0];
	spr.base_color[0][1] = ap->base_color[0][1];
	spr.base_color[0][2] = ap->base_color[0][2];
	spr.base_color[0][3] = ap->base_color[0][3];
	spr.scale[X] *= ap->FONT_SIZE;
	spr.scale[Y] = spr.scale[X];
	spr.uv_rect = font_rect;

	while ( string_box != 0xff )
	{
		spr.anime_no = string_box;

		if (string_box > 0xbb)
		{
			spr.tex_no = TEXTURE_FONT_AS;
			font_scale = 0.25f;
		}
		else
		{
			spr.tex_no = TEXTURE_FONT_JS;
			font_scale = 1.0f;
		}

		switch (string_box)
		{
			case 0xfe:
				//空白
				spr.pos[X] += (FONT_TEXTURE_SIZE * ap->FONT_INTERVAL_X) * ap->FONT_SIZE;
				break;

			case 0xfd:
				//改行
				spr.pos[X] = ap->pos[X];
				spr.pos[Y] += ( FONT_TEXTURE_SIZE * ap->FONT_INTERVAL_Y )* ap->FONT_SIZE;
				//string_addr += STRING_MAX_DATA - pop_font_counter - 1;
				pop_font_counter = -1;
				break;

			case 0xfc:
				//文字の色の変更
				pop_font_counter++;
				string_addr++;
				string_box = *string_addr;
				spr.base_color[ 0 ][ 0 ] = string_box;
				/*if( ap->workF[X] != 0 )//２回め
				{
					ap->workF[X] = 0;
					spr.base_color[0][0] = 255;
					spr.base_color[0][1] = 255;
					spr.base_color[0][2] = 255;
					spr.base_color[0][3] = 255;
				}
				else
				{
					ap->workF[X] = 1;
					spr.base_color[0][0] = ap->workE[X];
					spr.base_color[0][1] = ap->workE[Y];
					spr.base_color[0][2] = ap->workE[Z];
					spr.base_color[0][3] = ap->workE[P];
				}*/
				break;

			case 0xfb:
				pop_font_counter++;
				string_addr++;
				string_box = *string_addr;
				spr.base_color[ 0 ][ 1 ] = string_box;
				break;

			case 0xfa:
				pop_font_counter++;
				string_addr++;
				string_box = *string_addr;
				spr.base_color[ 0 ][ 2 ] = string_box;
				break;

			case 0xf9:
				pop_font_counter++;
				string_addr++;
				string_box = *string_addr;
				spr.base_color[ 0 ][ 3 ] = string_box;
				break;

			default:
				if (string_box < 0xd4)
				{
					spr.scale[X] *= font_scale;
					spr.scale[Y] *= font_scale;
					DRAW_default_func( &spr );
					spr.scale[X] /= font_scale;
					spr.scale[Y] /= font_scale;
					if (string_box >= 0xbc)
					{
						spr.pos[X] += ( ALPHABET_TEXTURE_SIZE * ap->FONT_INTERVAL_X ) * ap->FONT_SIZE * font_scale;
					}
					else
					{
						spr.pos[X] += ( FONT_TEXTURE_SIZE * ap->FONT_INTERVAL_X ) * ap->FONT_SIZE * font_scale;	
					}
				}
				break;
		}
		pop_font_counter++;
		string_addr++;
		string_box = *string_addr;
	}
}

//-------------------------------------------------------------------------------------------------
//	文字列の表示
//	font_sizeは1.0でdefaultの文字の大きさになる
//	font_INTERVALは1.0fでdefaultと同じ間隔になる
//-------------------------------------------------------------------------------------------------
TASK* font_pop_start( FUNC prg_point, FLOAT point_x, FLOAT point_y, FLOAT font_size, FLOAT font_interval_x, FLOAT font_interval_y, SINT32* string)
{
	TASK* ap;
	ap = TASK_start( prg_point, "テキストの表示" );
	ap->drawfunc = font_pop_drawfunc;
	ap->pos[X] = point_x;
	ap->pos[Y] = point_y;
	ap->FONT_SIZE = font_size;
	ap->FONT_INTERVAL_X = font_interval_x;
	ap->FONT_INTERVAL_Y = font_interval_y;
	ap->pri = PRI_FONT;
	ap->work_p[X] = string;
	ap->workF[X] = 0;		//色の変更用フラグ
	ap->workE[X] = 0xff;
	ap->workE[Y] = 0xff;
	ap->workE[Z] = 0xff;
	ap->workE[P] = 0xff;
	return ap;
}

//-------------------------------------------------------------------------------------------------
//	数字をだすときの専門
//	ap->work1[X]を変えると数字が変わる
//-------------------------------------------------------------------------------------------------
void font_pop_default_number_drawfunc(TASK* ap)
{
	TASK spr;
	SINT8 str[256];
	SINT32 number;
	SINT32 num_digit = 10;
	SINT32 roop = 0;

	number = ap->work1[X];

	TASK_init( &spr );
	spr.pos[X] = ap->pos[X];
	spr.pos[Y] = ap->pos[Y];
	spr.base_color[0][0] = ap->base_color[0][0];
	spr.base_color[0][1] = ap->base_color[0][1];
	spr.base_color[0][2] = ap->base_color[0][2];
	spr.base_color[0][3] = ap->base_color[0][3];
	spr.scale[X] = ap->FONT_SIZE;
	spr.scale[Y] = ap->FONT_SIZE;
	spr.tex_no = TEXTURE_FONT_JS;
	spr.uv_rect = font_rect;

	do
	{
		spr.anime_no = number % num_digit;
		spr.anime_no += 0xaf;
		//SOZ_to_g_spr( NULL, &spr );
		DRAW_default_func( &spr );
		number /= num_digit;
		roop++;
		spr.pos[X] -= 48.0f * ap->FONT_INTERVAL_X * ap->FONT_SIZE;
	} while (number > 0 && roop < 10 );


#ifdef DEBUG
	/*sprintf(str, "x : %f y: %f num %d", ap->pos[X], ap->pos[Y], ap->work1[X]);
	SOZ_debug_string(1.0f, 8.0f, str);*/

#endif // DEBUG

}

TASK* font_pop_number(FUNC prg_point, FLOAT point_x, FLOAT point_y, FLOAT font_size, SINT32 number)
{
	TASK* ap;

	ap = TASK_start(prg_point, "数字の表示");
	ap->drawfunc = font_pop_default_number_drawfunc;
	ap->pos[X] = point_x;
	ap->pos[Y] = point_y;
	
	ap->FONT_SIZE = font_size;
	ap->FONT_INTERVAL_X = 1.0f;
	ap->FONT_INTERVAL_Y = 1.0f;
	ap->CURSOR_POINT = 0;
	ap->pri = PRI_FONT + 5;
	ap->work1[X] = number;
	ap->work1[Y] = 0;

	return ap;
}

//-------------------------------------------------------------------------------------------------
//	簡単に文字を出力できるように
//	細かい設定はできない
//-------------------------------------------------------------------------------------------------
void font_pop_default( FLOAT point_x, FLOAT point_y, FLOAT font_size, SINT32 *string )
{
	font_pop_start( NULL, point_x, point_y, font_size, 1.0f, 1.0f,  string );
}

